### ISSUE TITLE
Homepage

### ISSUE THREAD

**Issue by indiandennis** [scalableinternetservices/swiper#2]
The homepages should list the current cheapest price for each dining hall. If the user is logged in it should list the user's open listings and have form that allows the user to create a new listing.

**Comment by kojiboji** [comment]
As a user or a guest, I should be able to see the eight dining locations; under each location, the open listing with the lowest price for that dining hall will be displayed. If I am logged in, on the right-hand side I should also see my pending reservations and a "create" button to add a new listing.
