### ISSUE TITLE
Style guide

### ISSUE THREAD

**Issue by kojiboji** [scalableinternetservices/swiper#9]
As a user, I should see a pretty app, so that I am enticed to eat food.

**Comment by chern** [comment]
Primary colors are purple and orange. See screenshot with navbar, buttons, and links updated to these colors.

<img width="1440" alt="Screen Shot 2019-10-31 at 2 25 10 PM" src="https://user-images.githubusercontent.com/12589878/67987337-5ba57580-fbea-11e9-8ef6-af11cf40061b.png">
